"$schema" = "https://starship.rs/config-schema.json"

add_newline = false

format = """\
$shell\
$kubernetes\
$git_branch\
$git_status\
$git_state\
$directory\
$character"""

[shell]
disabled = false
fish_indicator = "[󰈺](bold yellow)"
zsh_indicator = "[󱐋](purple)"
powershell_indicator = "[󰚥](bold blue)"

[kubernetes]
disabled = false
symbol = "󱃾"
style = "bold blue"
format = "[$symbol $context]($style) "

[git_branch]
symbol = ""
format = "[$symbol $branch]($style) "

[directory]
format = "[$path]($style)$read_only"

[character]
format = "$symbol"
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
